import { type NextPage } from "next";
import Head from "next/head";
import React from "react";
import Navbar from '../components/Navbar'


const Layout: NextPage = (props:any) => {
  return (
    <>
      <Head>
        <title>CineMarmot</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      {props.children}
    </>
  );
};

export default Layout;