import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import React, { useState } from "react";
import Navbar from '../components/Navbar'
import { trpc } from "../utils/trpc";
import MovieListPage from "./MovieListPage";
import HomePage from "./HomePage";
import { BrowserRouter as Router, Route, Routes, Link } from 'react-router-dom'


const Layout: NextPage = (props:any) => {
  return (
    <>
      <Head>
        <title>CineMarmot</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      {props.children}
    </>
  );
};

export default Layout;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <>
      <p className="text-center text-2xl text-stone-400 mt-8 mb-2">
        {sessionData ? `Hi ${sessionData.user?.name}, choose your seat!` : "Buy a ticket, go to the cinema, and enjoy the movie!"}
      </p>
    </>
  );
};